from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

from .capability_registry import CAPABILITY_REGISTRY

METHOD_RE = re.compile(r'^\s*(?:#\s*|["\']{0,3})method:\s*(.+?)\s*["\']{0,3}\s*$')


EXACT_MAP: dict[str, str] = {
    "from_gram": "constructor.from_gram",
    "A": "constructor.root",
    "B": "constructor.root",
    "C": "constructor.root",
    "D": "constructor.root",
    "E": "constructor.root",
    "F": "constructor.root",
    "G": "constructor.root",
    "A_affine": "constructor.root",
    "B_affine": "constructor.root",
    "C_affine": "constructor.root",
    "D_affine": "constructor.root",
    "E_affine": "constructor.root",
    "F_affine": "constructor.root",
    "G_affine": "constructor.root",
    "hyperbolic": "constructor.hyperbolic",
    "U": "constructor.hyperbolic",
    "H": "constructor.hyperbolic",
    "I": "constructor.hyperbolic",
    "II": "constructor.hyperbolic",
    "rank": "invariant.rank",
    "degree": "invariant.rank",
    "signature": "invariant.signature",
    "signature_tuple": "invariant.signature",
    "signature_pair": "invariant.signature",
    "determinant": "invariant.determinant",
    "det": "invariant.determinant",
    "discriminant": "invariant.discriminant",
    "disc": "invariant.discriminant",
    "pairing": "pairing.bilinear",
    "bilinear": "pairing.bilinear",
    "norm": "element.norm",
    "minimum": "enumeration.minimum_kissing",
    "kissing_number": "enumeration.minimum_kissing",
    "short_vectors": "enumeration.short_vectors",
    "shortest_vectors": "enumeration.short_vectors",
    "shortest_vector": "enumeration.short_vectors",
    "close_vectors": "enumeration.closest_vectors",
    "closest_vector": "enumeration.closest_vectors",
    "LLL": "reduction.lll",
    "lll": "reduction.lll",
    "BKZ": "reduction.bkz_hkz",
    "HKZ": "reduction.bkz_hkz",
    "orthogonal_group": "isometry.orthogonal_group",
    "automorphisms": "isometry.orthogonal_group",
    "orbit": "isometry.orbits_stabilizers",
    "same_orbit": "isometry.orbits_stabilizers",
    "stabilizer": "isometry.orbits_stabilizers",
    "has_isotropic_vector": "indefinite.isotropic_vectors",
    "isotropic_vector": "indefinite.isotropic_vectors",
    "primitive_isotropic_vectors": "indefinite.isotropic_vectors",
    "isotropic_orbit_representatives": "indefinite.isotropic_vectors",
    "witt_index": "indefinite.witt",
    "is_indefinite": "indefinite.witt",
    "sublattice": "substructure.sublattice",
    "orthogonal_complement": "substructure.sublattice",
    "perp": "substructure.sublattice",
    "quotient": "substructure.quotient",
    "dual": "substructure.dual",
    "dual_lattice": "substructure.dual",
    "discriminant_group": "discriminant.group",
    "value_module": "discriminant.forms",
    "value_module_qf": "discriminant.forms",
    "quadratic": "discriminant.forms",
    "orthogonal_hyperplane": "root.orthogonal_hyperplane",
    "reflection": "root.reflection",
    "vinberg": "coxeter.vinberg",
    "is_isomorphic": "root_system.isomorphism",
    "genus": "genus.local_global",
    "local_symbol": "genus.local_global",
    "local_density": "genus.local_global",
    "mass": "genus.local_global",
    "hnf": "nemo.normal_forms",
    "hnf_with_transform": "nemo.normal_forms",
    "snf": "nemo.normal_forms",
    "snf_with_transform": "nemo.normal_forms",
    "HermiteNormalFormIntegerMat": "nemo.normal_forms",
    "SmithNormalFormIntegerMat": "nemo.normal_forms",
    "OK": "number_field.algorithms",
    "^": "matrix.linear_algebra",
    "HermiteNormalFormIntegerMatTransform": "nemo.normal_forms",
    "SmithNormalFormIntegerMatTransforms": "nemo.normal_forms",
    "NullspaceIntMat": "matrix.linear_algebra",
    "SolutionIntMat": "matrix.linear_algebra",
    "SolutionNullspaceIntMat": "matrix.linear_algebra",
    "BaseIntMat": "matrix.linear_algebra",
    "BaseIntersectionIntMats": "matrix.linear_algebra",
    "ComplementIntMat": "matrix.linear_algebra",
    "OrthogonalEmbeddings": "interface.conversions",
    "integer_lattice": "constructor.from_gram",
    "lattice": "constructor.from_gram",
    "quadratic_lattice": "constructor.from_gram",
    "root_lattice": "constructor.root",
    "hyperbolic_plane_lattice": "constructor.hyperbolic",
    "ambient_space": "module.structure",
    "basis_matrix": "module.structure",
    "rational_span": "module.structure",
    "direct_sum": "module.structure",
    "direct_product": "module.structure",
    "biproduct": "module.structure",
    "intersect": "module.structure",
    "is_sublattice": "module.structure",
    "primitive_closure": "module.structure",
    "maximal_integral_lattice": "module.structure",
    "orthogonal_submodule": "module.structure",
    "lattice_in_same_ambient_space": "module.structure",
    "quadratic_space": "interface.conversions",
    "rational_representative": "interface.conversions",
    "representative": "combinatorics.enumeration",
    "representatives": "combinatorics.enumeration",
    "integer_genera": "combinatorics.enumeration",
    "genus_representatives": "combinatorics.enumeration",
    "vectors_by_length": "combinatorics.enumeration",
    "theta_series": "combinatorics.enumeration",
    "theta_series_degree_2": "combinatorics.enumeration",
    "representation_number_list": "combinatorics.enumeration",
    "representation_vector_list": "combinatorics.enumeration",
    "primitive_embeddings": "combinatorics.enumeration",
    "class_group": "number_field.algorithms",
    "class_number": "number_field.algorithms",
    "unit_group": "number_field.algorithms",
    "units": "number_field.algorithms",
    "ring_of_integers": "number_field.algorithms",
    "integral_basis": "number_field.algorithms",
    "ideal": "number_field.algorithms",
    "fractional_ideal": "number_field.algorithms",
    "residue_field": "number_field.algorithms",
    "valuation": "number_field.algorithms",
    "places": "number_field.algorithms",
    "real_places": "number_field.algorithms",
    "real_embeddings": "number_field.algorithms",
    "complex_embeddings": "number_field.algorithms",
    "galois_group": "number_field.algorithms",
    "galois_closure": "number_field.algorithms",
    "absolute_field": "number_field.algorithms",
    "absolute_polynomial": "number_field.algorithms",
    "absolute_degree": "number_field.algorithms",
    "absolute_discriminant": "number_field.algorithms",
    "relative_degree": "number_field.algorithms",
    "relative_polynomial": "number_field.algorithms",
    "trace_pairing": "number_field.algorithms",
    "trace_dual_basis": "number_field.algorithms",
    "zeta": "number_field.algorithms",
    "zeta_order": "number_field.algorithms",
    "is_galois": "number_field.algorithms",
    "is_relative": "number_field.algorithms",
    "is_totally_real": "number_field.algorithms",
    "is_totally_imaginary": "number_field.algorithms",
    "minkowski_reduction": "quadratic_form.transformations",
    "minkowski_reduction_for_4vars__SP": "quadratic_form.transformations",
    "reduced_form": "quadratic_form.transformations",
    "reduced_binary_form": "quadratic_form.transformations",
    "reduced_binary_form1": "quadratic_form.transformations",
    "reduced_ternary_form__Dickson": "quadratic_form.transformations",
    "matrix_action_left": "quadratic_form.transformations",
    "matrix_action_right": "quadratic_form.transformations",
    "swap_variables": "quadratic_form.transformations",
    "multiply_variable": "quadratic_form.transformations",
    "divide_variable": "quadratic_form.transformations",
    "extract_variables": "quadratic_form.transformations",
    "elementary_substitution": "quadratic_form.transformations",
    "add_symmetric": "quadratic_form.transformations",
    "local_density": "quadratic_form.local_algorithms",
    "local_density_congruence": "quadratic_form.local_algorithms",
    "local_good_density_congruence": "quadratic_form.local_algorithms",
    "local_good_density_congruence_even": "quadratic_form.local_algorithms",
    "local_good_density_congruence_odd": "quadratic_form.local_algorithms",
    "local_bad_density_congruence": "quadratic_form.local_algorithms",
    "local_badI_density_congruence": "quadratic_form.local_algorithms",
    "local_badII_density_congruence": "quadratic_form.local_algorithms",
    "local_primitive_density": "quadratic_form.local_algorithms",
    "local_primitive_density_congruence": "quadratic_form.local_algorithms",
    "local_zero_density_congruence": "quadratic_form.local_algorithms",
    "local_genus_symbol": "quadratic_form.local_algorithms",
    "local_symbol": "quadratic_form.local_algorithms",
    "conway_species_list_at_2": "quadratic_form.local_algorithms",
    "conway_species_list_at_odd_prime": "quadratic_form.local_algorithms",
    "conway_mass": "quadratic_form.local_algorithms",
    "conway_p_mass": "quadratic_form.local_algorithms",
    "conway_standard_mass": "quadratic_form.local_algorithms",
    "conway_standard_p_mass": "quadratic_form.local_algorithms",
    "toric_lattice": "toric.lattice_geometry",
    "cone_from_integrallattice_basis_matrix": "toric.lattice_geometry",
    "integrallattice_from_toriclattice_basis_matrix": "toric.lattice_geometry",
    "integrallattice_from_toriclattice_parent": "toric.lattice_geometry",
    "cone_dual": "toric.lattice_geometry",
    "torsion_quadratic_module": "discriminant.group",
    "abelian_group": "module.structure",
    "bilinear_map": "pairing.bilinear",
    "block_sum": "module.structure",
    "complex_point": "number_field.algorithms",
    "content": "invariant.discriminant",
    "extension": "number_field.algorithms",
    "randomize": "matrix.linear_algebra",
    "reciprocal": "number_field.algorithms",
    "trace": "number_field.algorithms",
}


KEYWORD_RULES: list[tuple[tuple[str, ...], str]] = [
    (("lll", "bkz", "hkz", "reduced", "babai"), "reduction.lll"),
    (("short", "minimum", "kissing", "voronoi", "closest"), "enumeration.short_vectors"),
    (("isotropic", "witt", "hyperbolic"), "indefinite.isotropic_vectors"),
    (("orbit", "stabilizer", "automorphism", "isometry"), "isometry.orbits_stabilizers"),
    (("root", "reflection", "coxeter", "vinberg"), "coxeter.vinberg"),
    (("genus", "local_", "hasse", "mass"), "genus.local_global"),
    (
        (
            "matrix",
            "kernel",
            "image",
            "solve",
            "echelon",
            "eigen",
            "charpoly",
            "rank",
            "nullity",
            "row",
            "column",
            "dense_",
            "sparse_",
            "pivot",
            "transpose",
            "adjoint",
            "anticommutator",
            "commutator",
            "cholesky",
            "hessenberg",
            "frobenius",
            "permanent",
            "linear_combination",
            "add_multiple",
            "with_added_multiple",
            "with_swapped",
            "swap_",
            "delete_",
            "insert_",
            "numpy",
            "lu",
            "adjugate",
            "augment",
            "diagonal",
            "rref",
            "ncols",
            "coefficient",
            "coefficients",
            "apply_map",
            "tensor_product",
            "trace_of_product",
            "inverse",
            "factor",
            "gcd",
            "minpoly",
            "characteristic",
        ),
        "matrix.linear_algebra",
    ),
    (
        (
            "field",
            "ideal",
            "prime",
            "class_",
            "unit",
            "embedding",
            "galois",
            "minkowski",
            "residue",
            "valuation",
            "order",
            "pari_",
            "hilbert_",
            "selmer",
            "zeta",
            "bach_bound",
            "dirichlet",
            "regulator",
            "conductor",
            "different",
            "decomposition",
            "primitive_element",
            "absolute_",
            "relative_",
            "completion",
            "complex_conjugation",
            "uniformizer",
            "abs_val",
            "omega",
            "divisor",
            "zeta_",
        ),
        "number_field.algorithms",
    ),
    (("quadratic_form", "conway_", "jordan_", "representation_", "neighbor", "theta_", "density", "p_neighbor"), "quadratic_form.local_algorithms"),
    (
        (
            "swap_",
            "multiply_",
            "divide_",
            "substitution",
            "extract_",
            "reduce",
            "minkowski",
            "complementary_subform",
            "clifford_",
            "count_congruence",
            "count_modp",
            "representation_",
            "basiclemma",
            "basic_lemma",
            "collect_small_blocks",
            "parity",
            "modulus_",
            "radical_",
            "quadratic_defect",
            "level",
            "siegel_product",
            "spinor_generators",
            "sum_by_coefficients_with",
            "compute_definiteness",
            "find_primitive_p_divisible_vector",
            "find_zeros_mod_p",
            "pseudorandom_primitive_zero_mod_p",
            "rational_diagonal_form",
            "symplectic_form",
            "xi",
            "xi_rec",
            "rook_vector",
            "primary_part",
            "form_class",
            "genera",
            "oddity",
            "excess",
        ),
        "quadratic_form.transformations",
    ),
    (
        (
            "submodule",
            "sublattice",
            "ambient",
            "span",
            "closure",
            "intersect",
            "direct_",
            "quotient",
            "module",
            "contains",
            "index",
            "primitive_closure",
            "maximal_overlattice",
            "overlattice",
            "saturation",
            "invariant_lattice",
            "coinvariant_lattice",
            "kernel_lattice",
            "zero_submodule",
            "lattice_in_same_ambient_space",
            "cardinality",
            "dimension",
            "dim",
            "dims",
            "structure",
            "relations",
            "gens",
            "gen",
            "primitive",
            "primitive_extensions",
            "scale",
            "rescale",
            "twist",
            "stack",
            "space",
            "with_rescaled_col",
            "scale_by_factor",
            "base_ring",
            "invariants",
            "invariant_bilinear_form",
            "dual_pairing",
            "maximum",
            "minimum",
            "max",
            "min",
        ),
        "module.structure",
    ),
    (("toric", "cone_", "polytope"), "toric.lattice_geometry"),
    (
        (
            "convert",
            "construction",
            "change_",
            "to_",
            "from_",
            "polynomial",
            "basis",
            "free_module",
            "quadratic_space",
            "rational_representative",
            "lattice",
            "integrallattice",
            "torsion_quadratic_module",
            "element_class",
            "element",
            "optimized_",
            "type",
        ),
        "interface.conversions",
    ),
    (
        (
            "representative",
            "representatives",
            "enumerate",
            "cycle",
            "orbits",
            "list",
            "items",
            "cover",
            "height",
            "principal",
            "scalar",
            "delta",
            "symmetry",
            "lmfdb_page",
            "relativize",
            "represents",
            "nonzero_positions",
        ),
        "combinatorics.enumeration",
    ),
    (("is_", "has_", "iseven"), "module.structure"),
    (("gram", "det", "disc", "signature"), "invariant.discriminant"),
    (("hnf", "snf", "normal", "smith", "hermite"), "nemo.normal_forms"),
]


def normalize_method_token(token: str) -> str:
    token = token.strip()
    token = token.strip('"').strip("'")
    token = token.replace("constructor(", "").replace(")", "")
    token = token.split("::", 1)[0]
    token = token.split("(", 1)[0]
    return token.strip().strip('"').strip("'")


def method_token_from_line(line: str) -> str | None:
    m = METHOD_RE.search(line)
    if not m:
        return None
    raw = m.group(1).strip()
    if raw == "runtime_coverage":
        return None
    return normalize_method_token(raw)


def map_method_to_capability(method: str) -> str:
    capability, _ = map_method_to_capability_with_reason(method)
    return capability


def map_method_to_capability_with_reason(method: str) -> tuple[str, str]:
    key = normalize_method_token(method)
    if key in EXACT_MAP:
        return EXACT_MAP[key], "exact"
    lower = key.lower()
    for words, capability in KEYWORD_RULES:
        if any(w in lower for w in words):
            return capability, "keyword"
    return "module.structure", "default"


def extract_method_tags(path: Path) -> list[str]:
    methods: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        token = method_token_from_line(line)
        if token:
            methods.append(token)
    return methods


def collect_method_tags(paths: list[Path]) -> set[str]:
    tags: set[str] = set()
    for path in paths:
        tags.update(extract_method_tags(path))
    return tags


@dataclass(frozen=True)
class ParityRow:
    method: str
    capability: str
    reason: str


def build_parity_rows(methods: set[str]) -> list[ParityRow]:
    rows = []
    for m in sorted(methods):
        capability, reason = map_method_to_capability_with_reason(m)
        rows.append(ParityRow(method=m, capability=capability, reason=reason))
    unknown = sorted({row.capability for row in rows} - set(CAPABILITY_REGISTRY))
    if unknown:
        raise AssertionError(f"Mapped to unknown capabilities: {unknown}")
    return rows
