from typing import Any

class LocalPath:
    def __getitem__(self, item: str | tuple[str, ...]) -> LocalCommand: ...

class LocalCommand:
    def __getitem__(self, item: str | tuple[str, ...]) -> LocalCommand: ...
    def __call__(self, *args: str, **kwargs: Any) -> tuple[int, str, str]: ...
    def run(
        self, _env: dict[str, str] | None = ..., retcode: int | None = ..., **kwargs: Any
    ) -> tuple[int, str, str]: ...

local: LocalPath
